# TagTuner on a Wemos D1 mini ESP32, PN532 over I2C.
# Only wiring and board specifics live here; behaviour is in the core packages.

substitutions:
  led_pin: "2"
  toggle_pin: "23"
  rotary_pin_a: "18"
  rotary_pin_b: "19"

packages:
  # project: github://luka6000/TagTuner/tagtuner-project.yaml@main
  # core-nfc: github://luka6000/TagTuner/tagtuner-core-nfc.yaml@main
  # core-comms: github://luka6000/TagTuner/tagtuner-core-comms.yaml@main
  project: !include tagtuner-project.yaml
  core-nfc: !include tagtuner-core-nfc.yaml
  core-comms: !include tagtuner-core-comms.yaml
  core-controls: !include tagtuner-core-controls.yaml
  core-led1: !include tagtuner-core-led1-binary.yaml

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_PM_ENABLE: 'Y'
      CONFIG_PM_DFS_INIT_AUTO: 'Y'
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ_80: 'Y'

# To be able to get logs from the device via serial and api.
logger:
  # level: VERBOSE
  level: DEBUG
  # level: WARN
  logs:
    light: WARN
    # pn532: DEBUG
    # pn532_i2c: DEBUG

i2c:
  id: bus_i2c
  sda: 21
  scl: 22
  scan: False
  frequency: 100kHz
  timeout: 13ms #to prevent pn532 timeout

esp32_ble_tracker:
  scan_parameters:
    active: false
bluetooth_proxy:
  active: false
